spring:
  application:
    name: vibecraft

  datasource:
    url: jdbc:postgresql://localhost:8000/vibecraftDB
    username: ${DB_USERNAME:User}
    password: ${DB_PASSWORD:Password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

jwt:
  secret-key: ${JWT_SECRET:as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl}
